### ISSUE TITLE
Design system > Datepicker > Need inline edit 

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#769] opened 2024-10-04 11:30 UTC
Design system > Datepicker > Need inline edit 

![Image](https://github.com/user-attachments/assets/b3d81e0b-f522-4a92-a0c8-74591d458722)

**Comment by suchithravipin1991** [comment] 2024-10-07 10:47
vaibhav implemented this cell edit in wunderbook

**Comment by suchithravipin1991** [comment] 2024-10-24 07:32
@trivenikulkarni : This fix need to be done at application level

**Comment by trivenikulkarni** [comment] 2024-10-24 09:15
@abhijeetjawale1  please connect to @suchithravipin1991  for details and fix this bug

**Comment by abhijeetjawale1** [comment] 2024-10-24 12:49
Closing this issue because the code is already implemented for inline editing the issue is in the css for the data table date picker should gets hidden back to the input.

**Closed as completed by abhijeetjawale1** 2024-10-24 12:49 UTC
Labels: Task, Application Issue
