### ISSUE TITLE
Design System > Version 8.3.3 > side nav bar > excess space is showing between two components

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#781] opened 2024-10-07 09:40 UTC
**Describe the bug**
excess space is showing between two components
 
**Steps to reproduce bug**

1.Go to 'side nav bar'
2. Navigate to 'api scope basic resource'
 
**Actual result-**
excess space is showing between two components
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/d103355a-be5d-415f-b67b-c86f7b1c8b18)

 
**Expected result-**
Excess space should not show between two components

**Comment by trivenikulkarni** [comment] 2024-10-11 12:14
Spacing still exists
![API_Scope_Staging_No_Issue](https://github.com/user-attachments/assets/f37c3e9b-32c0-430b-a582-03d3de77dcae)
![API_Scope_Dev](https://github.com/user-attachments/assets/da6e1c90-f10a-40cd-a029-8c1892d0b795)

**Comment by abhijeetjawale1** [comment] 2024-10-16 08:57
The issue was previously caused by someone hiding duplicate components a few days ago. I have now resolved the problem, which stemmed from the class being applied only to the child tags and not the parent, resulting in unwanted spacing. Additionally, the names of the hidden components will now be displayed while searching for components, and that has also been fixed

**Comment by rameshwarkamandar** [comment] 2024-10-18 05:52
Fixed on dev
![image](https://github.com/user-attachments/assets/daefb575-7156-44a3-967a-3de68feba3b5)

**Closed as completed by rameshwarkamandar** 2024-10-18 05:52 UTC
Labels: Bug

**Comment by RadhikaB123** [comment] 2024-12-02 11:58
Fixed on staging
![image](https://github.com/user-attachments/assets/019f5177-4859-4d48-b007-e7ce79d544de)
